/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkSecureString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CkSecureString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkSecureString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkSecureString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkSecureString() {
    this(chilkatJNI.new_CkSecureString(), true);
  }

  public boolean get_LastMethodSuccess() {
    return chilkatJNI.CkSecureString_get_LastMethodSuccess(swigCPtr, this);
  }

  public void put_LastMethodSuccess(boolean newVal) {
    chilkatJNI.CkSecureString_put_LastMethodSuccess(swigCPtr, this, newVal);
  }

  public void get_MaintainHash(CkString str) {
    chilkatJNI.CkSecureString_get_MaintainHash(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String maintainHash() {
    return chilkatJNI.CkSecureString_maintainHash(swigCPtr, this);
  }

  public void put_MaintainHash(String newVal) {
    chilkatJNI.CkSecureString_put_MaintainHash(swigCPtr, this, newVal);
  }

  public boolean get_ReadOnly() {
    return chilkatJNI.CkSecureString_get_ReadOnly(swigCPtr, this);
  }

  public void put_ReadOnly(boolean newVal) {
    chilkatJNI.CkSecureString_put_ReadOnly(swigCPtr, this, newVal);
  }

  public boolean Access(CkString outStr) {
    return chilkatJNI.CkSecureString_Access(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String access() {
    return chilkatJNI.CkSecureString_access(swigCPtr, this);
  }

  public boolean Append(String str) {
    return chilkatJNI.CkSecureString_Append(swigCPtr, this, str);
  }

  public boolean AppendSb(CkStringBuilder sb) {
    return chilkatJNI.CkSecureString_AppendSb(swigCPtr, this, CkStringBuilder.getCPtr(sb), sb);
  }

  public boolean AppendSecure(CkSecureString secStr) {
    return chilkatJNI.CkSecureString_AppendSecure(swigCPtr, this, CkSecureString.getCPtr(secStr), secStr);
  }

  public boolean HashVal(String encoding, CkString outStr) {
    return chilkatJNI.CkSecureString_HashVal(swigCPtr, this, encoding, CkString.getCPtr(outStr), outStr);
  }

  public String hashVal(String encoding) {
    return chilkatJNI.CkSecureString_hashVal(swigCPtr, this, encoding);
  }

  public boolean LoadFile(String path, String charset) {
    return chilkatJNI.CkSecureString_LoadFile(swigCPtr, this, path, charset);
  }

  public boolean SecStrEquals(CkSecureString secStr) {
    return chilkatJNI.CkSecureString_SecStrEquals(swigCPtr, this, CkSecureString.getCPtr(secStr), secStr);
  }

  public boolean VerifyHash(String hashVal, String encoding) {
    return chilkatJNI.CkSecureString_VerifyHash(swigCPtr, this, hashVal, encoding);
  }

}
