/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkXmlDSigGen {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CkXmlDSigGen(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkXmlDSigGen obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkXmlDSigGen(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkXmlDSigGen() {
    this(chilkatJNI.new_CkXmlDSigGen(), true);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkXmlDSigGen_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkXmlDSigGen_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkXmlDSigGen_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_Behaviors(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_Behaviors(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String behaviors() {
    return chilkatJNI.CkXmlDSigGen_behaviors(swigCPtr, this);
  }

  public void put_Behaviors(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_Behaviors(swigCPtr, this, newVal);
  }

  public void get_CustomKeyInfoXml(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_CustomKeyInfoXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String customKeyInfoXml() {
    return chilkatJNI.CkXmlDSigGen_customKeyInfoXml(swigCPtr, this);
  }

  public void put_CustomKeyInfoXml(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_CustomKeyInfoXml(swigCPtr, this, newVal);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkXmlDSigGen_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public void get_IncNamespacePrefix(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_IncNamespacePrefix(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String incNamespacePrefix() {
    return chilkatJNI.CkXmlDSigGen_incNamespacePrefix(swigCPtr, this);
  }

  public void put_IncNamespacePrefix(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_IncNamespacePrefix(swigCPtr, this, newVal);
  }

  public void get_IncNamespaceUri(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_IncNamespaceUri(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String incNamespaceUri() {
    return chilkatJNI.CkXmlDSigGen_incNamespaceUri(swigCPtr, this);
  }

  public void put_IncNamespaceUri(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_IncNamespaceUri(swigCPtr, this, newVal);
  }

  public void get_KeyInfoId(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_KeyInfoId(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String keyInfoId() {
    return chilkatJNI.CkXmlDSigGen_keyInfoId(swigCPtr, this);
  }

  public void put_KeyInfoId(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_KeyInfoId(swigCPtr, this, newVal);
  }

  public void get_KeyInfoKeyName(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_KeyInfoKeyName(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String keyInfoKeyName() {
    return chilkatJNI.CkXmlDSigGen_keyInfoKeyName(swigCPtr, this);
  }

  public void put_KeyInfoKeyName(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_KeyInfoKeyName(swigCPtr, this, newVal);
  }

  public void get_KeyInfoType(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_KeyInfoType(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String keyInfoType() {
    return chilkatJNI.CkXmlDSigGen_keyInfoType(swigCPtr, this);
  }

  public void put_KeyInfoType(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_KeyInfoType(swigCPtr, this, newVal);
  }

  public void get_LastErrorHtml(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkXmlDSigGen_lastErrorHtml(swigCPtr, this);
  }

  public void get_LastErrorText(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkXmlDSigGen_lastErrorText(swigCPtr, this);
  }

  public void get_LastErrorXml(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkXmlDSigGen_lastErrorXml(swigCPtr, this);
  }

  public boolean get_LastMethodSuccess() {
    return chilkatJNI.CkXmlDSigGen_get_LastMethodSuccess(swigCPtr, this);
  }

  public void put_LastMethodSuccess(boolean newVal) {
    chilkatJNI.CkXmlDSigGen_put_LastMethodSuccess(swigCPtr, this, newVal);
  }

  public void get_SigId(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SigId(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sigId() {
    return chilkatJNI.CkXmlDSigGen_sigId(swigCPtr, this);
  }

  public void put_SigId(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SigId(swigCPtr, this, newVal);
  }

  public void get_SigLocation(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SigLocation(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sigLocation() {
    return chilkatJNI.CkXmlDSigGen_sigLocation(swigCPtr, this);
  }

  public void put_SigLocation(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SigLocation(swigCPtr, this, newVal);
  }

  public void get_SigNamespacePrefix(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SigNamespacePrefix(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sigNamespacePrefix() {
    return chilkatJNI.CkXmlDSigGen_sigNamespacePrefix(swigCPtr, this);
  }

  public void put_SigNamespacePrefix(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SigNamespacePrefix(swigCPtr, this, newVal);
  }

  public void get_SigNamespaceUri(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SigNamespaceUri(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sigNamespaceUri() {
    return chilkatJNI.CkXmlDSigGen_sigNamespaceUri(swigCPtr, this);
  }

  public void put_SigNamespaceUri(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SigNamespaceUri(swigCPtr, this, newVal);
  }

  public void get_SignedInfoCanonAlg(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SignedInfoCanonAlg(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String signedInfoCanonAlg() {
    return chilkatJNI.CkXmlDSigGen_signedInfoCanonAlg(swigCPtr, this);
  }

  public void put_SignedInfoCanonAlg(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SignedInfoCanonAlg(swigCPtr, this, newVal);
  }

  public void get_SignedInfoDigestMethod(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SignedInfoDigestMethod(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String signedInfoDigestMethod() {
    return chilkatJNI.CkXmlDSigGen_signedInfoDigestMethod(swigCPtr, this);
  }

  public void put_SignedInfoDigestMethod(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SignedInfoDigestMethod(swigCPtr, this, newVal);
  }

  public void get_SignedInfoId(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SignedInfoId(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String signedInfoId() {
    return chilkatJNI.CkXmlDSigGen_signedInfoId(swigCPtr, this);
  }

  public void put_SignedInfoId(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SignedInfoId(swigCPtr, this, newVal);
  }

  public void get_SignedInfoPrefixList(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SignedInfoPrefixList(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String signedInfoPrefixList() {
    return chilkatJNI.CkXmlDSigGen_signedInfoPrefixList(swigCPtr, this);
  }

  public void put_SignedInfoPrefixList(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SignedInfoPrefixList(swigCPtr, this, newVal);
  }

  public void get_SigningAlg(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SigningAlg(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String signingAlg() {
    return chilkatJNI.CkXmlDSigGen_signingAlg(swigCPtr, this);
  }

  public void put_SigningAlg(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SigningAlg(swigCPtr, this, newVal);
  }

  public void get_SigValueId(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_SigValueId(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sigValueId() {
    return chilkatJNI.CkXmlDSigGen_sigValueId(swigCPtr, this);
  }

  public void put_SigValueId(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_SigValueId(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkXmlDSigGen_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkXmlDSigGen_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkXmlDSigGen_version(swigCPtr, this);
  }

  public void get_X509Type(CkString str) {
    chilkatJNI.CkXmlDSigGen_get_X509Type(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String x509Type() {
    return chilkatJNI.CkXmlDSigGen_x509Type(swigCPtr, this);
  }

  public void put_X509Type(String newVal) {
    chilkatJNI.CkXmlDSigGen_put_X509Type(swigCPtr, this, newVal);
  }

  public boolean AddEnvelopedRef(String id, CkStringBuilder content, String digestMethod, String canonMethod, String refType) {
    return chilkatJNI.CkXmlDSigGen_AddEnvelopedRef(swigCPtr, this, id, CkStringBuilder.getCPtr(content), content, digestMethod, canonMethod, refType);
  }

  public boolean AddExternalBinaryRef(String uri, CkBinData content, String digestMethod, String refType) {
    return chilkatJNI.CkXmlDSigGen_AddExternalBinaryRef(swigCPtr, this, uri, CkBinData.getCPtr(content), content, digestMethod, refType);
  }

  public boolean AddExternalFileRef(String uri, String localFilePath, String digestMethod, String refType) {
    return chilkatJNI.CkXmlDSigGen_AddExternalFileRef(swigCPtr, this, uri, localFilePath, digestMethod, refType);
  }

  public boolean AddExternalTextRef(String uri, CkStringBuilder content, String charset, boolean includeBom, String digestMethod, String refType) {
    return chilkatJNI.CkXmlDSigGen_AddExternalTextRef(swigCPtr, this, uri, CkStringBuilder.getCPtr(content), content, charset, includeBom, digestMethod, refType);
  }

  public boolean AddExternalXmlRef(String uri, CkStringBuilder content, String digestMethod, String canonMethod, String refType) {
    return chilkatJNI.CkXmlDSigGen_AddExternalXmlRef(swigCPtr, this, uri, CkStringBuilder.getCPtr(content), content, digestMethod, canonMethod, refType);
  }

  public boolean AddObject(String id, String content, String mimeType, String encoding) {
    return chilkatJNI.CkXmlDSigGen_AddObject(swigCPtr, this, id, content, mimeType, encoding);
  }

  public boolean AddObjectRef(String id, String digestMethod, String canonMethod, String prefixList, String refType) {
    return chilkatJNI.CkXmlDSigGen_AddObjectRef(swigCPtr, this, id, digestMethod, canonMethod, prefixList, refType);
  }

  public boolean AddSameDocRef(String id, String digestMethod, String canonMethod, String prefixList, String refType) {
    return chilkatJNI.CkXmlDSigGen_AddSameDocRef(swigCPtr, this, id, digestMethod, canonMethod, prefixList, refType);
  }

  public boolean AddSignatureNamespace(String nsPrefix, String nsUri) {
    return chilkatJNI.CkXmlDSigGen_AddSignatureNamespace(swigCPtr, this, nsPrefix, nsUri);
  }

  public boolean ConstructSignedInfo(CkStringBuilder sbXml, CkString outStr) {
    return chilkatJNI.CkXmlDSigGen_ConstructSignedInfo(swigCPtr, this, CkStringBuilder.getCPtr(sbXml), sbXml, CkString.getCPtr(outStr), outStr);
  }

  public String constructSignedInfo(CkStringBuilder sbXml) {
    return chilkatJNI.CkXmlDSigGen_constructSignedInfo(swigCPtr, this, CkStringBuilder.getCPtr(sbXml), sbXml);
  }

  public boolean CreateXmlDSig(String inXml, CkString outStr) {
    return chilkatJNI.CkXmlDSigGen_CreateXmlDSig(swigCPtr, this, inXml, CkString.getCPtr(outStr), outStr);
  }

  public String createXmlDSig(String inXml) {
    return chilkatJNI.CkXmlDSigGen_createXmlDSig(swigCPtr, this, inXml);
  }

  public boolean CreateXmlDSigSb(CkStringBuilder sbXml) {
    return chilkatJNI.CkXmlDSigGen_CreateXmlDSigSb(swigCPtr, this, CkStringBuilder.getCPtr(sbXml), sbXml);
  }

  public boolean SaveLastError(String path) {
    return chilkatJNI.CkXmlDSigGen_SaveLastError(swigCPtr, this, path);
  }

  public boolean SetHmacKey(String key, String encoding) {
    return chilkatJNI.CkXmlDSigGen_SetHmacKey(swigCPtr, this, key, encoding);
  }

  public boolean SetPrivateKey(CkPrivateKey privKey) {
    return chilkatJNI.CkXmlDSigGen_SetPrivateKey(swigCPtr, this, CkPrivateKey.getCPtr(privKey), privKey);
  }

  public boolean SetRefIdAttr(String uri_or_id, String value) {
    return chilkatJNI.CkXmlDSigGen_SetRefIdAttr(swigCPtr, this, uri_or_id, value);
  }

  public boolean SetX509Cert(CkCert cert, boolean usePrivateKey) {
    return chilkatJNI.CkXmlDSigGen_SetX509Cert(swigCPtr, this, CkCert.getCPtr(cert), cert, usePrivateKey);
  }

}
